
CREATE DATABASE db_SanatorioMedico;

CREATE TABLE Tbl_Sucursales
(
    CodigoSucursal        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NombreSucursal        VARCHAR(100) NOT NULL,
    Direccion             VARCHAR(200) NOT NULL,
    FechaApertura         DATE NOT NULL,
    HoraApertura          TIME NOT NULL,
    PresupuestoMensual    DECIMAL(12,2) NOT NULL,
    Estado                BOOLEAN NOT NULL
);

CREATE TABLE Tbl_Roles
(

    CodigoRol             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    NombreRol             VARCHAR(80) NOT NULL,
    DescripcionRol        VARCHAR(250) NULL,
    ModuloPrincipal       VARCHAR(100) NULL,
    PermiteConsultar      BOOLEAN NOT NULL,
    PermiteAgregar        BOOLEAN NOT NULL,
    PermiteEditar         BOOLEAN NOT NULL,
    PermiteAnular         BOOLEAN NOT NULL,
    Estado                VARCHAR(20) NOT NULL
);

CREATE TABLE Tbl_Colaboradores
(

    CodigoColaborador     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoSucursal        INT NOT NULL,
    CodigoRol             INT NOT NULL,
    Nombres               VARCHAR(100) NOT NULL,
    Apellidos             VARCHAR(100) NOT NULL,
    DPI                    VARCHAR(20) NOT NULL,
    NumeroColegiado       VARCHAR(30) NULL,
    TipoColaborador       VARCHAR(50) NOT NULL,
    Telefono              VARCHAR(20) NOT NULL,
    CorreoElectronico     VARCHAR(120) NULL,
    Direccion             VARCHAR(200) NULL,
    FechaContratacion     DATE NOT NULL,
    NombreUsuario         VARCHAR(80) NOT NULL,
    ClaveAcceso           VARCHAR(255) NOT NULL,
    Estado                VARCHAR(20) NOT NULL,

    CONSTRAINT FK_Colaboradores_Sucursales FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursales (CodigoSucursal),
    CONSTRAINT FK_Colaboradores_Roles FOREIGN KEY (CodigoRol) REFERENCES Tbl_Roles (CodigoRol)
);

CREATE TABLE Tbl_Pacientes
(

    CodigoPaciente        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    NumeroExpediente      VARCHAR(30) NOT NULL,
    TipoDocumento         VARCHAR(30) NOT NULL,
    NumeroDocumento       VARCHAR(25) NOT NULL,
    Nombres               VARCHAR(100) NOT NULL,
    Apellidos             VARCHAR(100) NOT NULL,
    FechaNacimiento       DATE NOT NULL,
    Genero                VARCHAR(20) NOT NULL,
    TipoSangre            VARCHAR(10) NULL,
    Telefono              VARCHAR(20) NOT NULL,
    CorreoElectronico     VARCHAR(120) NULL,
    Direccion             VARCHAR(200) NOT NULL,
    ContactoEmergencia    VARCHAR(150) NULL,
    TelefonoEmergencia    VARCHAR(20) NULL,
    Alergias              VARCHAR(500) NULL,
    Estado                VARCHAR(20) NOT NULL
);

CREATE TABLE Tbl_Especialidades
(

    CodigoEspecialidad    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    NombreEspecialidad    VARCHAR(100) NOT NULL,
    Descripcion           VARCHAR(250) NULL,
    AreaMedica            VARCHAR(100) NULL,
    DuracionConsulta      INT NULL,
    CostoConsulta         DECIMAL(12,2) NULL,
    RequiereCita          BOOLEAN NOT NULL,
    Observaciones         VARCHAR(250) NULL,
    Estado                VARCHAR(20) NOT NULL
);

CREATE TABLE Tbl_ColaboradoresEspecialidades
(

    CodigoColaboradorEspecialidad INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoColaborador             INT NOT NULL,
    CodigoEspecialidad            INT NOT NULL,
    FechaAsignacion               DATE NOT NULL,
    NumeroAutorizacion            VARCHAR(50) NULL,
    InstitucionAcreditadora       VARCHAR(150) NULL,
    FechaVencimiento              DATE NULL,
    Observaciones                 VARCHAR(250) NULL,
    Estado                        VARCHAR(20) NOT NULL,

    CONSTRAINT FK_ColaboradoresEspecialidades_Colaboradores FOREIGN KEY (CodigoColaborador) REFERENCES Tbl_Colaboradores (CodigoColaborador),
    CONSTRAINT FK_ColaboradoresEspecialidades_Especialidades FOREIGN KEY (CodigoEspecialidad) REFERENCES Tbl_Especialidades (CodigoEspecialidad)
);

CREATE TABLE Tbl_Horarios
(

    CodigoHorario         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoColaborador     INT NOT NULL,
    CodigoSucursal        INT NOT NULL,
    CodigoEspecialidad    INT NOT NULL,
    DiaSemana             VARCHAR(20) NOT NULL,
    HoraInicio            TIME NOT NULL,
    HoraFin               TIME NOT NULL,
    DuracionCitaMinutos   INT NOT NULL,
    Jornada               VARCHAR(30) NULL,
    Observaciones         VARCHAR(250) NULL,
    Estado                VARCHAR(20) NOT NULL,

    CONSTRAINT FK_Horarios_Colaboradores FOREIGN KEY (CodigoColaborador) REFERENCES Tbl_Colaboradores (CodigoColaborador),
    CONSTRAINT FK_Horarios_Sucursales FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursales (CodigoSucursal),
    CONSTRAINT FK_Horarios_Especialidades FOREIGN KEY (CodigoEspecialidad) REFERENCES Tbl_Especialidades (CodigoEspecialidad)
);

CREATE TABLE Tbl_CitasConsultas
(

    CodigoCitaConsulta    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoPaciente        INT NOT NULL,
    CodigoColaborador     INT NOT NULL,
    CodigoSucursal        INT NOT NULL,
    CodigoEspecialidad    INT NOT NULL,
    FechaHoraCita         TIMESTAMP NOT NULL,
    TipoAtencion          VARCHAR(30) NOT NULL,
    MotivoConsulta        VARCHAR(500) NOT NULL,
    Sintomas              VARCHAR(1000) NULL,
    ObservacionesMedicas  VARCHAR(1000) NULL,
    TratamientoGeneral    VARCHAR(1000) NULL,
    PresionArterial       VARCHAR(20) NULL,
    Temperatura           DECIMAL(5,2) NULL,
    Peso                  DECIMAL(6,2) NULL,
    Estado                VARCHAR(30) NOT NULL,

    CONSTRAINT FK_CitasConsultas_Pacientes FOREIGN KEY (CodigoPaciente) REFERENCES Tbl_Pacientes (CodigoPaciente),
    CONSTRAINT FK_CitasConsultas_Colaboradores FOREIGN KEY (CodigoColaborador) REFERENCES Tbl_Colaboradores (CodigoColaborador),
    CONSTRAINT FK_CitasConsultas_Sucursales FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursales (CodigoSucursal),
    CONSTRAINT FK_CitasConsultas_Especialidades FOREIGN KEY (CodigoEspecialidad) REFERENCES Tbl_Especialidades (CodigoEspecialidad)
);

CREATE TABLE Tbl_CitasConsultasDetalle
(

    CodigoDetalle         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoCitaConsulta    INT NOT NULL,
    CodigoProducto        INT NULL,
    TipoDetalle           VARCHAR(40) NOT NULL,
    SubtipoDetalle        VARCHAR(100) NULL,
    DescripcionDetalle    VARCHAR(1000) NOT NULL,
    Dosis                 VARCHAR(100) NULL,
    Frecuencia            VARCHAR(100) NULL,
    Duracion              VARCHAR(100) NULL,
    Indicaciones          VARCHAR(500) NULL,
    Resultado             VARCHAR(1000) NULL,
    Cantidad              DECIMAL(12,2) NULL,
    FechaRegistro         TIMESTAMP NOT NULL,
    Estado                VARCHAR(20) NOT NULL,

    CONSTRAINT FK_CitasConsultasDetalle_CitasConsultas FOREIGN KEY (CodigoCitaConsulta) REFERENCES Tbl_CitasConsultas (CodigoCitaConsulta)
);

CREATE TABLE Tbl_Habitaciones
(

    CodigoHabitacion      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoSucursal        INT NOT NULL,
    NumeroHabitacion      VARCHAR(20) NOT NULL,
    CodigoCama            VARCHAR(20) NOT NULL,
    TipoHabitacion        VARCHAR(50) NOT NULL,
    Piso                  VARCHAR(20) NULL,
    Capacidad             INT NOT NULL,
    TarifaDiaria          DECIMAL(12,2) NOT NULL,
    Descripcion           VARCHAR(250) NULL,
    Estado                VARCHAR(30) NOT NULL,

    CONSTRAINT FK_Habitaciones_Sucursales FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursales (CodigoSucursal)
);

CREATE TABLE Tbl_Hospitalizaciones
(

    CodigoHospitalizacion INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoPaciente        INT NOT NULL,
    CodigoSucursal        INT NOT NULL,
    CodigoColaborador     INT NOT NULL,
    CodigoCitaConsulta    INT NULL,
    CodigoHabitacion      INT NOT NULL,
    FechaHoraIngreso      TIMESTAMP NOT NULL,
    FechaHoraEgreso       TIMESTAMP NULL,
    MotivoIngreso         VARCHAR(500) NOT NULL,
    DiagnosticoIngreso    VARCHAR(500) NULL,
    DiagnosticoEgreso     VARCHAR(500) NULL,
    RecomendacionesEgreso VARCHAR(1000) NULL,
    Observaciones         VARCHAR(1000) NULL,
    Estado                VARCHAR(30) NOT NULL,

    CONSTRAINT FK_Hospitalizaciones_Pacientes FOREIGN KEY (CodigoPaciente) REFERENCES Tbl_Pacientes (CodigoPaciente),
    CONSTRAINT FK_Hospitalizaciones_Sucursales FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursales (CodigoSucursal),
    CONSTRAINT FK_Hospitalizaciones_Colaboradores FOREIGN KEY (CodigoColaborador) REFERENCES Tbl_Colaboradores (CodigoColaborador),
    CONSTRAINT FK_Hospitalizaciones_CitasConsultas FOREIGN KEY (CodigoCitaConsulta) REFERENCES Tbl_CitasConsultas (CodigoCitaConsulta),
    CONSTRAINT FK_Hospitalizaciones_Habitaciones FOREIGN KEY (CodigoHabitacion) REFERENCES Tbl_Habitaciones (CodigoHabitacion)
);

CREATE TABLE Tbl_Productos
(

    CodigoProducto        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoInterno         VARCHAR(30) NOT NULL,
    NombreProducto        VARCHAR(150) NOT NULL,
    TipoProducto          VARCHAR(50) NOT NULL,
    Categoria             VARCHAR(100) NOT NULL,
    Presentacion          VARCHAR(100) NULL,
    UnidadMedida          VARCHAR(50) NOT NULL,
    PrincipioActivo       VARCHAR(150) NULL,
    Concentracion         VARCHAR(100) NULL,
    PrecioCompra          DECIMAL(12,2) NOT NULL,
    PrecioVenta           DECIMAL(12,2) NOT NULL,
    RequiereReceta        BOOLEAN NOT NULL,
    Estado                VARCHAR(20) NOT NULL
);

ALTER TABLE Tbl_CitasConsultasDetalle ADD CONSTRAINT FK_CitasConsultasDetalle_Productos FOREIGN KEY (CodigoProducto) REFERENCES Tbl_Productos (CodigoProducto);

CREATE TABLE Tbl_Proveedores
(

    CodigoProveedor       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    NIT                    VARCHAR(20) NOT NULL,
    RazonSocial           VARCHAR(150) NOT NULL,
    NombreComercial       VARCHAR(150) NULL,
    Direccion             VARCHAR(200) NOT NULL,
    Municipio             VARCHAR(100) NULL,
    Departamento          VARCHAR(100) NULL,
    Telefono              VARCHAR(20) NOT NULL,
    CorreoElectronico     VARCHAR(120) NULL,
    PersonaContacto       VARCHAR(150) NULL,
    TelefonoContacto      VARCHAR(20) NULL,
    Estado                VARCHAR(20) NOT NULL
);

CREATE TABLE Tbl_MovimientosInventario
(

    CodigoMovimientoInventario INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoSucursal             INT NOT NULL,
    CodigoProducto             INT NOT NULL,
    CodigoProveedor            INT NULL,
    CodigoColaborador          INT NOT NULL,
    FechaHoraMovimiento        TIMESTAMP NOT NULL,
    TipoMovimiento             VARCHAR(40) NOT NULL,
    NumeroDocumento            VARCHAR(50) NULL,
    Lote                       VARCHAR(50) NULL,
    FechaVencimiento           DATE NULL,
    CantidadEntrada            DECIMAL(12,2) NULL,
    CantidadSalida             DECIMAL(12,2) NULL,
    CostoUnitario              DECIMAL(12,2) NULL,
    ExistenciaResultante       DECIMAL(12,2) NOT NULL,
    MotivoMovimiento           VARCHAR(250) NULL,
    Observaciones              VARCHAR(500) NULL,
    Estado                     VARCHAR(20) NOT NULL,

    CONSTRAINT FK_MovimientosInventario_Sucursales FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursales (CodigoSucursal),
    CONSTRAINT FK_MovimientosInventario_Productos FOREIGN KEY (CodigoProducto) REFERENCES Tbl_Productos (CodigoProducto),
    CONSTRAINT FK_MovimientosInventario_Proveedores FOREIGN KEY (CodigoProveedor) REFERENCES Tbl_Proveedores (CodigoProveedor),
    CONSTRAINT FK_MovimientosInventario_Colaboradores FOREIGN KEY (CodigoColaborador) REFERENCES Tbl_Colaboradores (CodigoColaborador)
);

CREATE TABLE Tbl_Facturas
(

    CodigoFactura         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoPaciente        INT NOT NULL,
    CodigoSucursal        INT NOT NULL,
    CodigoColaborador     INT NOT NULL,
    NumeroFactura         VARCHAR(50) NOT NULL,
    FechaHoraFactura      TIMESTAMP NOT NULL,
    NombreFacturacion     VARCHAR(150) NOT NULL,
    NITFacturacion        VARCHAR(20) NOT NULL,
    DireccionFacturacion  VARCHAR(200) NULL,
    Subtotal              DECIMAL(12,2) NOT NULL,
    Descuento             DECIMAL(12,2) NOT NULL,
    Impuesto              DECIMAL(12,2) NOT NULL,
    Total                 DECIMAL(12,2) NOT NULL,
    SaldoPendiente        DECIMAL(12,2) NOT NULL,
    Estado                VARCHAR(30) NOT NULL,

    CONSTRAINT FK_Facturas_Pacientes FOREIGN KEY (CodigoPaciente) REFERENCES Tbl_Pacientes (CodigoPaciente),
    CONSTRAINT FK_Facturas_Sucursales FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursales (CodigoSucursal),
    CONSTRAINT FK_Facturas_Colaboradores FOREIGN KEY (CodigoColaborador) REFERENCES Tbl_Colaboradores (CodigoColaborador)
);

CREATE TABLE Tbl_FacturasDetalle
(

    CodigoFacturaDetalle  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CodigoFactura         INT NOT NULL,
    TipoMovimiento        VARCHAR(30) NOT NULL,
    TipoCargo             VARCHAR(50) NULL,
    Concepto              VARCHAR(250) NOT NULL,
    Cantidad              DECIMAL(12,2) NULL,
    PrecioUnitario        DECIMAL(12,2) NULL,
    Subtotal              DECIMAL(12,2) NULL,
    MontoPago             DECIMAL(12,2) NULL,
    FormaPago             VARCHAR(50) NULL,
    ReferenciaPago        VARCHAR(100) NULL,
    CodigoReferenciaOrigen INT NULL,
    FechaHoraRegistro     TIMESTAMP NOT NULL,
    Observaciones         VARCHAR(500) NULL,
    Estado                VARCHAR(20) NOT NULL,

    CONSTRAINT FK_FacturasDetalle_Facturas FOREIGN KEY (CodigoFactura) REFERENCES Tbl_Facturas (CodigoFactura)
);
